name: createtag.yml
on: push

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set APP_VERSION
        id: set_version
        run: echo "APP_VERSION=$(sh setversion.sh)" >> $GITHUB_ENV

      - name: Create Tag
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git tag ${{ env.APP_VERSION }} ${{ github.sha }} -m "Release ${{ env.APP_VERSION }}"
          git push origin ${{ env.APP_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
