
name: Build release
on: push

env:
  PRE_PATH: ""

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'

      - name: Set APP_VERSION
        id: set_version
        run: echo "APP_VERSION=$(sh setversion.sh)" >> $GITHUB_ENV

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOPRIVATE: "github.com/codio/*"
          APP_VERSION: ${{ env.APP_VERSION }}

      - name: Tar Folder
        run: tar czf ../release.tgz ./
        working-directory: dist

      - name: Upload To Artifactory
        run: curl --fail -i -u"${BINARY_REPOSITORY_CREDENTIALS}" -T release.tgz "${BINARY_REPOSITORY_URL}/component-builds/govnc-${GIT_HASH}.tar.gz"
        env:
          BINARY_REPOSITORY_URL: ${{ secrets.BINARY_REPOSITORY_URL }}
          GIT_HASH: ${{ github.sha }}
          BINARY_REPOSITORY_CREDENTIALS: ${{ secrets.BINARY_REPOSITORY_USER }}:${{ secrets.BINARY_REPOSITORY_PASSWORD }}
